# Generated by Django 3.0.2 on 2020-01-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_auto_20200112_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
