# Generated by Django 3.0.2 on 2020-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0006_auto_20200124_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='createDT',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='notitle 24_01_2020_20_03', max_length=256),
        ),
    ]
