# Generated by Django 3.0.2 on 2020-01-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0008_auto_20200124_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='user_photo01'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='notitle 25_01_2020_20_58', max_length=256),
        ),
    ]
