# Generated by Django 3.0.2 on 2020-01-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0009_auto_20200125_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteApp.Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default='notitle 25_01_2020_22_31', max_length=256),
        ),
    ]
